### ISSUE TITLE
GWT compilation errors when trying to use this library

### ISSUE THREAD

**Issue by salvadordiaz** [adrianmsmith/gwt-time#2]
Hi,
I'm trying to get this project moving forward to a state where it could actually be included in the standard gwt library but I can't even get a simple gwt project to compile.

**Steps to reproduce:**
- Checkout the simplest possible project making use of this library:

`git clone git@github.com:salvadordiaz/gwt-time-demo.git`
- Try to run a GWT compilation (everything is setup with maven):

`mvn install`
- Watch it fail with errors in located in source code coming from the gwt-time jar:

```
[INFO]    [ERROR] Errors in 'jar:file:/home/salvador/.m2/repository/com/google/gwt/gwt-time/2.6.1-SNAPSHOT/gwt-time-2.6.1-SNAPSHOT.jar!/com/google/gwt/emul/java/time/ZoneId.java'
[INFO]       [ERROR] Line 383: No source code is available for type java.util.Locale; did you forget to inherit a required module?
[INFO]    [ERROR] Errors in 'jar:file:/home/salvador/.m2/repository/com/google/gwt/gwt-time/2.6.1-SNAPSHOT/gwt-time-2.6.1-SNAPSHOT.jar!/com/google/gwt/emul/java/time/ZoneOffset.java'
[INFO]       [ERROR] Line 81: No source code is available for type java.util.concurrent.ConcurrentMap<K,V>; did you forget to inherit a required module?
[INFO]       [ERROR] Line 81: No source code is available for type java.util.concurrent.ConcurrentHashMap<K,V>; did you forget to inherit a required module?
```

**Possible fixes:**
I'm the guy that [offered to take the time to contribute to the project](https://code.google.com/p/google-web-toolkit/issues/detail?id=603#c95) in order to get it in shape for inclusion in the official gwt distribution. I tried to make it work but I'm getting GWT compilation errors that I'm pretty sure you're not seeing because the project where you're using gwt-time [has all the JRE-emulated classes](https://github.com/m-m-m/mmm/tree/master/mmm-util/mmm-util-gwt/src/main/resources/net/sf/mmm/util/gwt) needed to make it compile. So here's what we could do to make this work:
- would you consider moving all this supersource stuff to a standalone project ?
- or shoud I just copy-paste the necessary classes in the gwt-time project ?

Thanks again for your time and for gwt-time ;)

**Comment by hohwille** [comment]
Too sad, I totally missed this out years ago. Your error was only missing source dependencies I assume. However, I think that GWT is not the big future anymore. Sad but true...
Thanks for your interest in supporting and improving. I might close done this repo in the future as I am not maintaining this stuff for years.
